version: '3.9'

services:
  dmdd-nginx:
    image: nginx:latest
    container_name: dmdd-nginx
    ports:
      - "80:80" # Expose nginx to the host
    volumes:
      - ./configs/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dmdd-public-network # Accessible externally
      - dmdd-internal-network # Communicate with other services

  dmdd-php-fpm:
    image: php:8.2-fpm
    container_name: dmdd-php-fpm
    volumes:
      - ./gui:/var/www/html
      - ./.env:/var/www/html/.env:ro
    networks:
      - dmdd-internal-network # Internal only

  dmdd-core:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: dmdd-core
    volumes:
      - ./core:/app
      - ./.env:/app/.env:ro
    networks:
      - dmdd-internal-network # Internal only
    command: >
      sh -c "python3 main.py"

networks:
  dmdd-public-network:
    driver: bridge
  dmdd-internal-network:
    driver: bridge
    internal: true
