version: '3.9'

services:
  dmdd-nginx:
    image: nginx:latest
    container_name: dmdd-nginx
    ports:
      - "9098:80" # Expose nginx to the host
    volumes:
      - ./.configs/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./gui/public/:/var/www/html/public/ # Serve static files
    networks:
      - dmdd-public-network # Accessible externally
      - dmdd-internal-network # Communicate with other services
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  dmdd-php-fpm:
    container_name: dmdd-php-fpm
    build:
      context: ./gui
      dockerfile: Dockerfile
    volumes:
      - ./gui:/var/www/html
      - .configs/php/php.ini:/usr/local/etc/php/php.ini
      - .configs/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm.conf
      - .env:/var/www/html/.env
    networks:
      - dmdd-internal-network # Internal only
      - dmdd-public-network # Accessible externally
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  dmdd-core:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: dmdd-core
    volumes:
      - ./core:/app
      - ${PWD}/.env:/app/.env:ro
    networks:
      - dmdd-internal-network # Internal only
      - dmdd-public-network # Accessible externally
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    command: >
        sh -c "PYTHONPATH=/app python3 -m main"


networks:
  dmdd-public-network:
    driver: bridge
  dmdd-internal-network:
    driver: bridge
    internal: true
