version: '3.9'

services:
  dmdd-nginx:
    image: nginx:latest
    container_name: dmdd-nginx
    ports:
      - "80:80"
    volumes:
      - .configs/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dmdd-network
    depends_on:
      - dmdd-php-fpm
      - dmdd-core

  dmdd-php-fpm:
    image: php:8.2-fpm
    container_name: dmdd-php-fpm
    volumes:
      - ./gui:/var/www/html
      - ./.env:/var/www/html/.env:ro
    networks:
      - dmdd-network

  dmdd-core:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: dmdd-core
    volumes:
      - ./core:/app
      - ./.env:/app/.env:ro
    networks:
      - dmdd-network
    command: >
      sh -c "gunicorn -w 4 -b 0.0.0.0:5000 main:daemon.app"

networks:
  dmdd-network:
    driver: bridge
    internal: true
